package restudio.resync.worldgen.registry;

import restudio.flow.data.FlowDataType;

import java.util.List;

public final class WorldGenNodeDefinitions {
    private WorldGenNodeDefinitions() {
    }

    public static void registerDefaults(WorldGenNodeRegistry registry) {
        registry.register(WorldGenNodeDefinition.builder("simplex", "Simplex").input("seed", FlowDataType.SEED, 0, "number").input("frequency", FlowDataType.FLOAT, 0.01f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("perlin", "Perlin").input("seed", FlowDataType.SEED, 0, "number").input("frequency", FlowDataType.FLOAT, 0.01f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("value", "Value").input("seed", FlowDataType.SEED, 0, "number").input("frequency", FlowDataType.FLOAT, 0.01f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("cellular", "Cellular").input("seed", FlowDataType.SEED, 0, "number").input("frequency", FlowDataType.FLOAT, 0.01f, "number").input("distance_func", FlowDataType.STRING, "euclidean", "dropdown").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("white", "White").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("fbm", "Fractal FBm").input("source", FlowDataType.FLOAT, 0f, "number").input("octaves", FlowDataType.FLOAT, 4f, "number").input("lacunarity", FlowDataType.FLOAT, 2f, "number").input("gain", FlowDataType.FLOAT, 0.5f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ridged", "Fractal Ridged").input("source", FlowDataType.FLOAT, 0f, "number").input("octaves", FlowDataType.FLOAT, 4f, "number").input("lacunarity", FlowDataType.FLOAT, 2f, "number").input("gain", FlowDataType.FLOAT, 0.5f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ping_pong", "Ping Pong").input("source", FlowDataType.FLOAT, 0f, "number").input("octaves", FlowDataType.FLOAT, 4f, "number").input("lacunarity", FlowDataType.FLOAT, 2f, "number").input("gain", FlowDataType.FLOAT, 0.5f, "number").input("ping_pong_strength", FlowDataType.FLOAT, 2f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("add", "Add").input("a", FlowDataType.FLOAT, 0f, "number").input("b", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("multiply", "Multiply").input("a", FlowDataType.FLOAT, 1f, "number").input("b", FlowDataType.FLOAT, 1f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("remap", "Remap").input("in", FlowDataType.FLOAT, 0f, "number").input("from_min", FlowDataType.FLOAT, -1f, "number").input("from_max", FlowDataType.FLOAT, 1f, "number").input("to_min", FlowDataType.FLOAT, 0f, "number").input("to_max", FlowDataType.FLOAT, 128f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("clamp", "Clamp").input("in", FlowDataType.FLOAT, 0f, "number").input("min", FlowDataType.FLOAT, 0f, "number").input("max", FlowDataType.FLOAT, 1f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("abs", "Abs").input("in", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("min", "Min").input("a", FlowDataType.FLOAT, 0f, "number").input("b", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("max", "Max").input("a", FlowDataType.FLOAT, 0f, "number").input("b", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("domain_warp_gradient", "Domain Warp Gradient").input("source", FlowDataType.FLOAT, 0f, "number").input("amplitude", FlowDataType.FLOAT, 1f, "number").input("frequency", FlowDataType.FLOAT, 0.01f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("domain_warp_simplex", "Domain Warp Simplex").input("source", FlowDataType.FLOAT, 0f, "number").input("amplitude", FlowDataType.FLOAT, 1f, "number").input("frequency", FlowDataType.FLOAT, 0.01f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("terrace", "Terrace").input("in", FlowDataType.FLOAT, 0f, "number").input("step_count", FlowDataType.FLOAT, 8f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("seed_offset", "Seed Offset").input("in", FlowDataType.FLOAT, 0f, "number").input("offset", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("continental_shelf", "Continental Shelf").input("scale", FlowDataType.FLOAT, 1f, "number").input("ocean", FlowDataType.FLOAT, 0.42f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("mountain_range", "Mountain Range").input("amount", FlowDataType.FLOAT, 1f, "number").input("scale", FlowDataType.FLOAT, 1f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("river_network", "River Network").input("density", FlowDataType.FLOAT, 1f, "number").input("depth", FlowDataType.FLOAT, 24f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("eroded_peaks", "Eroded Peaks").input("amount", FlowDataType.FLOAT, 1f, "number").input("terraces", FlowDataType.FLOAT, 12f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("badlands_plateau", "Badlands Plateau").input("height", FlowDataType.FLOAT, 86f, "number").input("erosion", FlowDataType.FLOAT, 0.55f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("volcanic_field", "Volcanic Field").input("height", FlowDataType.FLOAT, 72f, "number").input("roughness", FlowDataType.FLOAT, 0.7f, "number").input("seed", FlowDataType.SEED, 0, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("density_from_height", "Density From Height").input("height", FlowDataType.FLOAT, 64f, "number").input("falloff", FlowDataType.FLOAT, 12f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("terrain_density", "Terrain Density").input("continentalness", FlowDataType.FLOAT, 0f, "number").input("erosion", FlowDataType.FLOAT, 0f, "number").input("weirdness", FlowDataType.FLOAT, 0f, "number").input("depth", FlowDataType.FLOAT, 0f, "number").input("base", FlowDataType.FLOAT, 64f, "number").input("seed", FlowDataType.SEED, 0, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("output_height", "Output Height").input("height", FlowDataType.FLOAT, 64f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_density", "Output Density").input("density", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_continentalness", "Output Continentalness").input("continentalness", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_erosion", "Output Erosion").input("erosion", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_weirdness", "Output Weirdness").input("weirdness", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_depth", "Output Depth").input("depth", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_temperature", "Output Temperature").input("temperature", FlowDataType.FLOAT, 0.5f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_humidity", "Output Humidity").input("humidity", FlowDataType.FLOAT, 0.5f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_biome", "Output Biome").input("biome", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input("temperature", FlowDataType.FLOAT, 0.5f, "number").input("humidity", FlowDataType.FLOAT, 0.5f, "number").input("keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").build());
        registry.register(WorldGenNodeDefinition.builder("output_block", "Output Block").input("block", FlowDataType.BLOCK, null, "material").input("y", FlowDataType.FLOAT, 0f, "number").input("replace", FlowDataType.FLOAT, 1f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("biome_constant", "Biome Constant").input("biome", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input("keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output("biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_profile", "Biome Profile").input("profile", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input("keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output("biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_select", "Biome Select").input("mask", FlowDataType.BOOLEAN, false, "toggle").input("true_biome", FlowDataType.BIOME, "minecraft:forest", "searchable", biomeOptions()).input("false_biome", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input("keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output("biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_blend", "Biome Blend").input("a", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input("b", FlowDataType.BIOME, "minecraft:forest", "searchable", biomeOptions()).input("weight", FlowDataType.FLOAT, 0.5f, "number").output("biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("climate_map", "Climate Map").input("temperature", FlowDataType.FLOAT, 0.5f, "number").input("humidity", FlowDataType.FLOAT, 0.5f, "number").input("keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input("keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output("biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_climate_router", "Biome Climate Router").input("temperature", FlowDataType.FLOAT, 0.5f, "number").input("humidity", FlowDataType.FLOAT, 0.5f, "number").input("continentalness", FlowDataType.FLOAT, 0f, "number").input("erosion", FlowDataType.FLOAT, 0f, "number").input("weirdness", FlowDataType.FLOAT, 0f, "number").input("temperature_scale", FlowDataType.FLOAT, 1f, "number").input("humidity_scale", FlowDataType.FLOAT, 1f, "number").input("keep_vanilla_features", FlowDataType.BOOLEAN, true, "toggle").input("keep_vanilla_structures", FlowDataType.BOOLEAN, true, "toggle").input("keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").input("seed", FlowDataType.SEED, 0, "number").output("biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("temperature", "Temperature").input("value", FlowDataType.FLOAT, 0.5f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("humidity", "Humidity").input("value", FlowDataType.FLOAT, 0.5f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("continentalness", "Continentalness").input("value", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("erosion", "Erosion").input("value", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("weirdness", "Weirdness").input("value", FlowDataType.FLOAT, 0f, "number").output("out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("surface_rule", "Surface Rule").input("top", FlowDataType.BLOCK, "minecraft:grass_block", "material").input("filler", FlowDataType.BLOCK, "minecraft:dirt", "material").output("surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("material_layer", "Material Layer").input("block", FlowDataType.BLOCK, "minecraft:stone", "material").input("depth", FlowDataType.FLOAT, 3f, "number").output("surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("height_band", "Height Band").input("min", FlowDataType.FLOAT, 0f, "number").input("max", FlowDataType.FLOAT, 320f, "number").output("mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("slope_mask", "Slope Mask").input("min", FlowDataType.FLOAT, 0f, "number").input("max", FlowDataType.FLOAT, 1f, "number").output("mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("beach_rule", "Beach Rule").input("sand", FlowDataType.BLOCK, "minecraft:sand", "material").output("surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("underwater_rule", "Underwater Rule").input("block", FlowDataType.BLOCK, "minecraft:gravel", "material").output("surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("snow_rule", "Snow Rule").input("block", FlowDataType.BLOCK, "minecraft:snow_block", "material").output("surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("cave_noise", "Cave Noise").input("seed", FlowDataType.SEED, 0, "number").input("frequency", FlowDataType.FLOAT, 0.02f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("worm_cave", "Worm Cave").input("radius", FlowDataType.FLOAT, 3f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("cheese_cave", "Cheese Cave").input("threshold", FlowDataType.FLOAT, 0.6f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ravine", "Ravine").input("width", FlowDataType.FLOAT, 6f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("carve_if", "Carve If").input("mask", FlowDataType.BOOLEAN, false, "toggle").input("density", FlowDataType.FLOAT, 0f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("density_combine", "Density Combine").input("a", FlowDataType.FLOAT, 0f, "number").input("b", FlowDataType.FLOAT, 0f, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("cave_system", "Cave System").input("amount", FlowDataType.FLOAT, 1f, "number").input("scale", FlowDataType.FLOAT, 1f, "number").input("seed", FlowDataType.SEED, 0, "number").output("density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ore_vein", "Ore Vein").input("block", FlowDataType.BLOCK, "minecraft:coal_ore", "material", List.of(), "Block Placed In The Vein").input("size", FlowDataType.FLOAT, 8f, "number", List.of(), "Average Blocks Per Vein").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("tree_feature", "Tree Feature").input("tree", FlowDataType.STRING, "TREE", "searchable", treeOptions(), "Vanilla Tree Configuration").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("vegetation_patch", "Vegetation Patch").input("block", FlowDataType.BLOCK, "minecraft:short_grass", "material", List.of(), "Plant Or Ground Block Used By The Patch").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("liquid_lake", "Liquid Lake").input("fluid", FlowDataType.BLOCK, "minecraft:water", "material", List.of(), "Fluid Used To Fill The Lake").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("disk", "Disk").input("block", FlowDataType.BLOCK, "minecraft:clay", "material", List.of(), "Block Used By The Disk").input("radius", FlowDataType.FLOAT, 4f, "number", List.of(), "Maximum Horizontal Radius").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("boulder", "Boulder").input("block", FlowDataType.BLOCK, "minecraft:mossy_cobblestone", "material", List.of(), "Block Used By The Boulder").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("placed_feature", "Catalog Feature").input("feature", FlowDataType.STRING, "minecraft:patch_grass", "searchable", List.of(), "Existing Placed Feature From The Selected Minecraft Version").output("feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("scatter", "Scatter").input("previous", FlowDataType.WORLDGEN_FEATURES, "", null, List.of(), "Earlier Placements In This Chain").input("feature", FlowDataType.WORLDGEN_FEATURE, "", null, List.of(), "Feature Added By This Placement").input("count", FlowDataType.FLOAT, 8f, "number", List.of(), "Placement Attempts Per Chunk").input("chance", FlowDataType.FLOAT, 1f, "number", List.of(), "Chance For Each Chunk From 0 To 1").input("min_y", FlowDataType.FLOAT, -64f, "number", List.of(), "Lowest Allowed Block Height").input("max_y", FlowDataType.FLOAT, 319f, "number", List.of(), "Highest Allowed Block Height").input("biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input("generation_step", FlowDataType.STRING, "vegetal_decoration", "dropdown", featureStages(), "Vanilla Generation Step Used By The Feature").input("override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Features In Matching Biomes").output("placement", FlowDataType.WORLDGEN_FEATURES).build());
        registry.register(WorldGenNodeDefinition.builder("poisson_scatter", "Poisson Scatter").input("previous", FlowDataType.WORLDGEN_FEATURES, "", null, List.of(), "Earlier Placements In This Chain").input("feature", FlowDataType.WORLDGEN_FEATURE, "", null, List.of(), "Feature Added By This Placement").input("spacing", FlowDataType.FLOAT, 12f, "number", List.of(), "Minimum Distance Between Placements").input("min_y", FlowDataType.FLOAT, -64f, "number", List.of(), "Lowest Allowed Block Height").input("max_y", FlowDataType.FLOAT, 319f, "number", List.of(), "Highest Allowed Block Height").input("biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input("generation_step", FlowDataType.STRING, "vegetal_decoration", "dropdown", featureStages(), "Vanilla Generation Step Used By The Feature").input("override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Features In Matching Biomes").output("placement", FlowDataType.WORLDGEN_FEATURES).build());
        registry.register(WorldGenNodeDefinition.builder("biome_filter", "Biome Filter").input("biome", FlowDataType.BIOME, "minecraft:plains", "dropdown").output("mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("height_filter", "Height Filter").input("min", FlowDataType.FLOAT, 0f, "number").input("max", FlowDataType.FLOAT, 320f, "number").output("mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("chance_filter", "Chance Filter").input("chance", FlowDataType.FLOAT, 0.5f, "number").input("salt", FlowDataType.SEED, 0, "number").output("mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("structure_placement", "Structure Placement").input("previous", FlowDataType.WORLDGEN_STRUCTURES, "", null, List.of(), "Earlier Structures In This Chain").input("structure_id", FlowDataType.STRING, "", "searchable", structureOptions(), "Vanilla Or ReSync Structure To Place").input("spacing", FlowDataType.FLOAT, 32f, "number", List.of(), "Average Distance Between Candidate Regions In Chunks").input("separation", FlowDataType.FLOAT, 8f, "number", List.of(), "Minimum Chunk Gap Inside A Candidate Region").input("salt", FlowDataType.SEED, 0, "number", List.of(), "Stable Randomization Salt").input("anchor", FlowDataType.STRING, "surface", "dropdown", List.of("surface", "origin", "buried"), "How The Structure's Vertical Origin Meets The Terrain").input("y_offset", FlowDataType.FLOAT, 0f, "number", List.of(), "Final Vertical Adjustment In Blocks").input("biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input("terrain_match", FlowDataType.BOOLEAN, true, "toggle", List.of(), "Reject Placements Across Unsafe Height Changes").input("override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Structures In Matching Biomes").output("structure", FlowDataType.WORLDGEN_STRUCTURES).build());
        registry.register(WorldGenNodeDefinition.builder("spawn_rule", "Spawn Rule").input("previous", FlowDataType.WORLDGEN_SPAWNS, "", null, List.of(), "Earlier Spawn Rules In This Chain").input("entity", FlowDataType.ENTITY_TYPE, "minecraft:zombie", "searchable", entityOptions(), "Entity Added By This Rule").input("category", FlowDataType.STRING, "monster", "dropdown", spawnCategories(), "Minecraft Spawn Category").input("weight", FlowDataType.FLOAT, 10f, "number", List.of(), "Relative Selection Weight").input("min_group", FlowDataType.FLOAT, 1f, "number", List.of(), "Smallest Spawn Group").input("max_group", FlowDataType.FLOAT, 4f, "number", List.of(), "Largest Spawn Group").input("biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input("min_y", FlowDataType.FLOAT, -64f, "number", List.of(), "Lowest Allowed Block Height").input("max_y", FlowDataType.FLOAT, 319f, "number", List.of(), "Highest Allowed Block Height").input("block_below", FlowDataType.BLOCK, "", "material", List.of(), "Optional Required Block Below The Spawn").input("min_light", FlowDataType.FLOAT, 0f, "number", List.of(), "Lowest Allowed Light Level").input("max_light", FlowDataType.FLOAT, 15f, "number", List.of(), "Highest Allowed Light Level").input("time", FlowDataType.STRING, "any", "dropdown", List.of("any", "day", "night"), "Allowed Time Of Day").input("weather", FlowDataType.STRING, "any", "dropdown", List.of("any", "clear", "rain", "thunder"), "Allowed Weather").input("override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Spawns In Matching Biomes").output("spawn", FlowDataType.WORLDGEN_SPAWNS).build());
        registry.register(WorldGenNodeDefinition.builder("output_features", "Output Features").input("placements", FlowDataType.WORLDGEN_FEATURES, "", null).build());
        registry.register(WorldGenNodeDefinition.builder("output_structures", "Output Structures").input("placements", FlowDataType.WORLDGEN_STRUCTURES, "", null).build());
        registry.register(WorldGenNodeDefinition.builder("output_spawns", "Output Spawns").input("table", FlowDataType.WORLDGEN_SPAWNS, "", null).build());
    }

    private static List<String> biomeOptions() {
        return List.of();
    }

    private static List<String> entityOptions() {
        return List.of();
    }

    private static List<String> treeOptions() {
        return List.of();
    }

    private static List<String> structureOptions() {
        return List.of();
    }

    private static List<String> featureStages() {
        return List.of("raw_generation", "lakes", "local_modifications", "underground_structures", "surface_structures", "strongholds",
            "underground_ores", "underground_decoration", "fluid_springs", "vegetal_decoration", "top_layer_modification");
    }

    private static List<String> spawnCategories() {
        return List.of("monster", "creature", "ambient", "axolotls", "underground_water_creature", "water_creature", "water_ambient", "misc");
    }
}
