package restudio.resync.worldgen.registry;

import restudio.flow.data.FlowDataType;
import restudio.resync.flow.identity.PinId;

import java.util.List;

public final class WorldGenNodeDefinitions {
    private WorldGenNodeDefinitions() {
    }

    public static void registerDefaults(WorldGenNodeRegistry registry) {
        for (WorldGenNodeDefinition definition : defaultDefinitions()) {
            registry.register(definition);
        }
    }

    public static List<WorldGenNodeDefinition> defaultDefinitions() {
        WorldGenNodeRegistry registry = new WorldGenNodeRegistry();
        registerDefinitionValues(registry);
        return List.copyOf(registry.getAllDefinitions());
    }

    private static void registerDefinitionValues(WorldGenNodeRegistry registry) {
        registry.register(WorldGenNodeDefinition.builder("simplex", "Simplex").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.01f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("perlin", "Perlin").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.01f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("value", "Value").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.01f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("cellular", "Cellular").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.01f, "number").input(PinId.of("distance_func"), "distance_func", FlowDataType.STRING, "euclidean", "dropdown").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("white", "White").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("fbm", "Fractal FBm").input(PinId.of("source"), "source", FlowDataType.FLOAT, 0f, "number").input(PinId.of("octaves"), "octaves", FlowDataType.FLOAT, 4f, "number").input(PinId.of("lacunarity"), "lacunarity", FlowDataType.FLOAT, 2f, "number").input(PinId.of("gain"), "gain", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ridged", "Fractal Ridged").input(PinId.of("source"), "source", FlowDataType.FLOAT, 0f, "number").input(PinId.of("octaves"), "octaves", FlowDataType.FLOAT, 4f, "number").input(PinId.of("lacunarity"), "lacunarity", FlowDataType.FLOAT, 2f, "number").input(PinId.of("gain"), "gain", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ping_pong", "Ping Pong").input(PinId.of("source"), "source", FlowDataType.FLOAT, 0f, "number").input(PinId.of("octaves"), "octaves", FlowDataType.FLOAT, 4f, "number").input(PinId.of("lacunarity"), "lacunarity", FlowDataType.FLOAT, 2f, "number").input(PinId.of("gain"), "gain", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("ping_pong_strength"), "ping_pong_strength", FlowDataType.FLOAT, 2f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("add", "Add").input(PinId.of("a"), "a", FlowDataType.FLOAT, 0f, "number").input(PinId.of("b"), "b", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("multiply", "Multiply").input(PinId.of("a"), "a", FlowDataType.FLOAT, 1f, "number").input(PinId.of("b"), "b", FlowDataType.FLOAT, 1f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("remap", "Remap").input(PinId.of("in"), "in", FlowDataType.FLOAT, 0f, "number").input(PinId.of("from_min"), "from_min", FlowDataType.FLOAT, -1f, "number").input(PinId.of("from_max"), "from_max", FlowDataType.FLOAT, 1f, "number").input(PinId.of("to_min"), "to_min", FlowDataType.FLOAT, 0f, "number").input(PinId.of("to_max"), "to_max", FlowDataType.FLOAT, 128f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("clamp", "Clamp").input(PinId.of("in"), "in", FlowDataType.FLOAT, 0f, "number").input(PinId.of("min"), "min", FlowDataType.FLOAT, 0f, "number").input(PinId.of("max"), "max", FlowDataType.FLOAT, 1f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("abs", "Abs").input(PinId.of("in"), "in", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("min", "Min").input(PinId.of("a"), "a", FlowDataType.FLOAT, 0f, "number").input(PinId.of("b"), "b", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("max", "Max").input(PinId.of("a"), "a", FlowDataType.FLOAT, 0f, "number").input(PinId.of("b"), "b", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("domain_warp_gradient", "Domain Warp Gradient").input(PinId.of("source"), "source", FlowDataType.FLOAT, 0f, "number").input(PinId.of("amplitude"), "amplitude", FlowDataType.FLOAT, 1f, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.01f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("domain_warp_simplex", "Domain Warp Simplex").input(PinId.of("source"), "source", FlowDataType.FLOAT, 0f, "number").input(PinId.of("amplitude"), "amplitude", FlowDataType.FLOAT, 1f, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.01f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("terrace", "Terrace").input(PinId.of("in"), "in", FlowDataType.FLOAT, 0f, "number").input(PinId.of("step_count"), "step_count", FlowDataType.FLOAT, 8f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("seed_offset", "Seed Offset").input(PinId.of("in"), "in", FlowDataType.FLOAT, 0f, "number").input(PinId.of("offset"), "offset", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("continental_shelf", "Continental Shelf").input(PinId.of("scale"), "scale", FlowDataType.FLOAT, 1f, "number").input(PinId.of("ocean"), "ocean", FlowDataType.FLOAT, 0.42f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("mountain_range", "Mountain Range").input(PinId.of("amount"), "amount", FlowDataType.FLOAT, 1f, "number").input(PinId.of("scale"), "scale", FlowDataType.FLOAT, 1f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("river_network", "River Network").input(PinId.of("density"), "density", FlowDataType.FLOAT, 1f, "number").input(PinId.of("depth"), "depth", FlowDataType.FLOAT, 24f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("eroded_peaks", "Eroded Peaks").input(PinId.of("amount"), "amount", FlowDataType.FLOAT, 1f, "number").input(PinId.of("terraces"), "terraces", FlowDataType.FLOAT, 12f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("badlands_plateau", "Badlands Plateau").input(PinId.of("height"), "height", FlowDataType.FLOAT, 86f, "number").input(PinId.of("erosion"), "erosion", FlowDataType.FLOAT, 0.55f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("volcanic_field", "Volcanic Field").input(PinId.of("height"), "height", FlowDataType.FLOAT, 72f, "number").input(PinId.of("roughness"), "roughness", FlowDataType.FLOAT, 0.7f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("density_from_height", "Density From Height").input(PinId.of("height"), "height", FlowDataType.FLOAT, 64f, "number").input(PinId.of("falloff"), "falloff", FlowDataType.FLOAT, 12f, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("terrain_density", "Terrain Density").input(PinId.of("continentalness"), "continentalness", FlowDataType.FLOAT, 0f, "number").input(PinId.of("erosion"), "erosion", FlowDataType.FLOAT, 0f, "number").input(PinId.of("weirdness"), "weirdness", FlowDataType.FLOAT, 0f, "number").input(PinId.of("depth"), "depth", FlowDataType.FLOAT, 0f, "number").input(PinId.of("base"), "base", FlowDataType.FLOAT, 64f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("output_height", "Output Height").input(PinId.of("height"), "height", FlowDataType.FLOAT, 64f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_density", "Output Density").input(PinId.of("density"), "density", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_continentalness", "Output Continentalness").input(PinId.of("continentalness"), "continentalness", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_erosion", "Output Erosion").input(PinId.of("erosion"), "erosion", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_weirdness", "Output Weirdness").input(PinId.of("weirdness"), "weirdness", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_depth", "Output Depth").input(PinId.of("depth"), "depth", FlowDataType.FLOAT, 0f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_temperature", "Output Temperature").input(PinId.of("temperature"), "temperature", FlowDataType.FLOAT, 0.5f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_humidity", "Output Humidity").input(PinId.of("humidity"), "humidity", FlowDataType.FLOAT, 0.5f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("output_biome", "Output Biome").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input(PinId.of("temperature"), "temperature", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("humidity"), "humidity", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("keep_vanilla_features"), "keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_structures"), "keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_spawns"), "keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").build());
        registry.register(WorldGenNodeDefinition.builder("output_block", "Output Block").input(PinId.of("block"), "block", FlowDataType.BLOCK, null, "material").input(PinId.of("y"), "y", FlowDataType.FLOAT, 0f, "number").input(PinId.of("replace"), "replace", FlowDataType.FLOAT, 1f, "number").build());
        registry.register(WorldGenNodeDefinition.builder("biome_constant", "Biome Constant").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input(PinId.of("keep_vanilla_features"), "keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_structures"), "keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_spawns"), "keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output(PinId.of("output_biome"), "biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_profile", "Biome Profile").input(PinId.of("profile"), "profile", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input(PinId.of("keep_vanilla_features"), "keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_structures"), "keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_spawns"), "keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output(PinId.of("biome"), "biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_select", "Biome Select").input(PinId.of("mask"), "mask", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("true_biome"), "true_biome", FlowDataType.BIOME, "minecraft:forest", "searchable", biomeOptions()).input(PinId.of("false_biome"), "false_biome", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input(PinId.of("keep_vanilla_features"), "keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_structures"), "keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_spawns"), "keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output(PinId.of("biome"), "biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_blend", "Biome Blend").input(PinId.of("a"), "a", FlowDataType.BIOME, "minecraft:plains", "searchable", biomeOptions()).input(PinId.of("b"), "b", FlowDataType.BIOME, "minecraft:forest", "searchable", biomeOptions()).input(PinId.of("weight"), "weight", FlowDataType.FLOAT, 0.5f, "number").output(PinId.of("biome"), "biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("climate_map", "Climate Map").input(PinId.of("temperature"), "temperature", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("humidity"), "humidity", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("keep_vanilla_features"), "keep_vanilla_features", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_structures"), "keep_vanilla_structures", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("keep_vanilla_spawns"), "keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").output(PinId.of("biome"), "biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("biome_climate_router", "Biome Climate Router").input(PinId.of("temperature"), "temperature", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("humidity"), "humidity", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("continentalness"), "continentalness", FlowDataType.FLOAT, 0f, "number").input(PinId.of("erosion"), "erosion", FlowDataType.FLOAT, 0f, "number").input(PinId.of("weirdness"), "weirdness", FlowDataType.FLOAT, 0f, "number").input(PinId.of("temperature_scale"), "temperature_scale", FlowDataType.FLOAT, 1f, "number").input(PinId.of("humidity_scale"), "humidity_scale", FlowDataType.FLOAT, 1f, "number").input(PinId.of("keep_vanilla_features"), "keep_vanilla_features", FlowDataType.BOOLEAN, true, "toggle").input(PinId.of("keep_vanilla_structures"), "keep_vanilla_structures", FlowDataType.BOOLEAN, true, "toggle").input(PinId.of("keep_vanilla_spawns"), "keep_vanilla_spawns", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("biome"), "biome", FlowDataType.BIOME).build());
        registry.register(WorldGenNodeDefinition.builder("temperature", "Temperature").input(PinId.of("value"), "value", FlowDataType.FLOAT, 0.5f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("humidity", "Humidity").input(PinId.of("value"), "value", FlowDataType.FLOAT, 0.5f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("continentalness", "Continentalness").input(PinId.of("value"), "value", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("erosion", "Erosion").input(PinId.of("value"), "value", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("weirdness", "Weirdness").input(PinId.of("value"), "value", FlowDataType.FLOAT, 0f, "number").output(PinId.of("out"), "out", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("surface_rule", "Surface Rule").input(PinId.of("top"), "top", FlowDataType.BLOCK, "minecraft:grass_block", "material").input(PinId.of("filler"), "filler", FlowDataType.BLOCK, "minecraft:dirt", "material").output(PinId.of("surface"), "surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("material_layer", "Material Layer").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:stone", "material").input(PinId.of("depth"), "depth", FlowDataType.FLOAT, 3f, "number").output(PinId.of("surface"), "surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("height_band", "Height Band").input(PinId.of("min"), "min", FlowDataType.FLOAT, 0f, "number").input(PinId.of("max"), "max", FlowDataType.FLOAT, 320f, "number").output(PinId.of("mask"), "mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("slope_mask", "Slope Mask").input(PinId.of("min"), "min", FlowDataType.FLOAT, 0f, "number").input(PinId.of("max"), "max", FlowDataType.FLOAT, 1f, "number").output(PinId.of("mask"), "mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("beach_rule", "Beach Rule").input(PinId.of("sand"), "sand", FlowDataType.BLOCK, "minecraft:sand", "material").output(PinId.of("surface"), "surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("underwater_rule", "Underwater Rule").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:gravel", "material").output(PinId.of("surface"), "surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("snow_rule", "Snow Rule").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:snow_block", "material").output(PinId.of("surface"), "surface", FlowDataType.BLOCK).build());
        registry.register(WorldGenNodeDefinition.builder("cave_noise", "Cave Noise").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").input(PinId.of("frequency"), "frequency", FlowDataType.FLOAT, 0.02f, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("worm_cave", "Worm Cave").input(PinId.of("radius"), "radius", FlowDataType.FLOAT, 3f, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("cheese_cave", "Cheese Cave").input(PinId.of("threshold"), "threshold", FlowDataType.FLOAT, 0.6f, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ravine", "Ravine").input(PinId.of("width"), "width", FlowDataType.FLOAT, 6f, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("carve_if", "Carve If").input(PinId.of("mask"), "mask", FlowDataType.BOOLEAN, false, "toggle").input(PinId.of("density"), "density", FlowDataType.FLOAT, 0f, "number").output(PinId.of("output_density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("density_combine", "Density Combine").input(PinId.of("a"), "a", FlowDataType.FLOAT, 0f, "number").input(PinId.of("b"), "b", FlowDataType.FLOAT, 0f, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("cave_system", "Cave System").input(PinId.of("amount"), "amount", FlowDataType.FLOAT, 1f, "number").input(PinId.of("scale"), "scale", FlowDataType.FLOAT, 1f, "number").input(PinId.of("seed"), "seed", FlowDataType.SEED, 0, "number").output(PinId.of("density"), "density", FlowDataType.FLOAT).build());
        registry.register(WorldGenNodeDefinition.builder("ore_vein", "Ore Vein").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:coal_ore", "material", List.of(), "Block Placed In The Vein").input(PinId.of("size"), "size", FlowDataType.FLOAT, 8f, "number", List.of(), "Average Blocks Per Vein").output(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("tree_feature", "Tree Feature").input(PinId.of("tree"), "tree", FlowDataType.STRING, "TREE", "searchable", treeOptions(), "Vanilla Tree Configuration").output(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("vegetation_patch", "Vegetation Patch").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:short_grass", "material", List.of(), "Plant Or Ground Block Used By The Patch").output(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("liquid_lake", "Liquid Lake").input(PinId.of("fluid"), "fluid", FlowDataType.BLOCK, "minecraft:water", "material", List.of(), "Fluid Used To Fill The Lake").output(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("disk", "Disk").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:clay", "material", List.of(), "Block Used By The Disk").input(PinId.of("radius"), "radius", FlowDataType.FLOAT, 4f, "number", List.of(), "Maximum Horizontal Radius").output(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("boulder", "Boulder").input(PinId.of("block"), "block", FlowDataType.BLOCK, "minecraft:mossy_cobblestone", "material", List.of(), "Block Used By The Boulder").output(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("placed_feature", "Catalog Feature").input(PinId.of("feature"), "feature", FlowDataType.STRING, "minecraft:patch_grass", "searchable", List.of(), "Existing Placed Feature From The Selected Minecraft Version").output(PinId.of("output_feature"), "feature", FlowDataType.WORLDGEN_FEATURE).build());
        registry.register(WorldGenNodeDefinition.builder("scatter", "Scatter").input(PinId.of("previous"), "previous", FlowDataType.WORLDGEN_FEATURES, "", null, List.of(), "Earlier Placements In This Chain").input(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE, "", null, List.of(), "Feature Added By This Placement").input(PinId.of("count"), "count", FlowDataType.FLOAT, 8f, "number", List.of(), "Placement Attempts Per Chunk").input(PinId.of("chance"), "chance", FlowDataType.FLOAT, 1f, "number", List.of(), "Chance For Each Chunk From 0 To 1").input(PinId.of("min_y"), "min_y", FlowDataType.FLOAT, -64f, "number", List.of(), "Lowest Allowed Block Height").input(PinId.of("max_y"), "max_y", FlowDataType.FLOAT, 319f, "number", List.of(), "Highest Allowed Block Height").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input(PinId.of("generation_step"), "generation_step", FlowDataType.STRING, "vegetal_decoration", "dropdown", featureStages(), "Vanilla Generation Step Used By The Feature").input(PinId.of("override_vanilla"), "override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Features In Matching Biomes").output(PinId.of("placement"), "placement", FlowDataType.WORLDGEN_FEATURES).build());
        registry.register(WorldGenNodeDefinition.builder("poisson_scatter", "Poisson Scatter").input(PinId.of("previous"), "previous", FlowDataType.WORLDGEN_FEATURES, "", null, List.of(), "Earlier Placements In This Chain").input(PinId.of("feature"), "feature", FlowDataType.WORLDGEN_FEATURE, "", null, List.of(), "Feature Added By This Placement").input(PinId.of("spacing"), "spacing", FlowDataType.FLOAT, 12f, "number", List.of(), "Minimum Distance Between Placements").input(PinId.of("min_y"), "min_y", FlowDataType.FLOAT, -64f, "number", List.of(), "Lowest Allowed Block Height").input(PinId.of("max_y"), "max_y", FlowDataType.FLOAT, 319f, "number", List.of(), "Highest Allowed Block Height").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input(PinId.of("generation_step"), "generation_step", FlowDataType.STRING, "vegetal_decoration", "dropdown", featureStages(), "Vanilla Generation Step Used By The Feature").input(PinId.of("override_vanilla"), "override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Features In Matching Biomes").output(PinId.of("placement"), "placement", FlowDataType.WORLDGEN_FEATURES).build());
        registry.register(WorldGenNodeDefinition.builder("biome_filter", "Biome Filter").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "minecraft:plains", "dropdown").output(PinId.of("mask"), "mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("height_filter", "Height Filter").input(PinId.of("min"), "min", FlowDataType.FLOAT, 0f, "number").input(PinId.of("max"), "max", FlowDataType.FLOAT, 320f, "number").output(PinId.of("mask"), "mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("chance_filter", "Chance Filter").input(PinId.of("chance"), "chance", FlowDataType.FLOAT, 0.5f, "number").input(PinId.of("salt"), "salt", FlowDataType.SEED, 0, "number").output(PinId.of("mask"), "mask", FlowDataType.BOOLEAN).build());
        registry.register(WorldGenNodeDefinition.builder("structure_placement", "Structure Placement").input(PinId.of("previous"), "previous", FlowDataType.WORLDGEN_STRUCTURES, "", null, List.of(), "Earlier Structures In This Chain").input(PinId.of("structure_id"), "structure_id", FlowDataType.STRING, "", "searchable", structureOptions(), "Vanilla Or ReSync Structure To Place").input(PinId.of("spacing"), "spacing", FlowDataType.FLOAT, 32f, "number", List.of(), "Average Distance Between Candidate Regions In Chunks").input(PinId.of("separation"), "separation", FlowDataType.FLOAT, 8f, "number", List.of(), "Minimum Chunk Gap Inside A Candidate Region").input(PinId.of("salt"), "salt", FlowDataType.SEED, 0, "number", List.of(), "Stable Randomization Salt").input(PinId.of("anchor"), "anchor", FlowDataType.STRING, "surface", "dropdown", List.of("surface", "origin", "buried"), "How The Structure's Vertical Origin Meets The Terrain").input(PinId.of("y_offset"), "y_offset", FlowDataType.FLOAT, 0f, "number", List.of(), "Final Vertical Adjustment In Blocks").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input(PinId.of("terrain_match"), "terrain_match", FlowDataType.BOOLEAN, true, "toggle", List.of(), "Reject Placements Across Unsafe Height Changes").input(PinId.of("override_vanilla"), "override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Structures In Matching Biomes").output(PinId.of("structure"), "structure", FlowDataType.WORLDGEN_STRUCTURES).build());
        registry.register(WorldGenNodeDefinition.builder("spawn_rule", "Spawn Rule").input(PinId.of("previous"), "previous", FlowDataType.WORLDGEN_SPAWNS, "", null, List.of(), "Earlier Spawn Rules In This Chain").input(PinId.of("entity"), "entity", FlowDataType.ENTITY_TYPE, "minecraft:zombie", "searchable", entityOptions(), "Entity Added By This Rule").input(PinId.of("category"), "category", FlowDataType.STRING, "monster", "dropdown", spawnCategories(), "Minecraft Spawn Category").input(PinId.of("weight"), "weight", FlowDataType.FLOAT, 10f, "number", List.of(), "Relative Selection Weight").input(PinId.of("min_group"), "min_group", FlowDataType.FLOAT, 1f, "number", List.of(), "Smallest Spawn Group").input(PinId.of("max_group"), "max_group", FlowDataType.FLOAT, 4f, "number", List.of(), "Largest Spawn Group").input(PinId.of("biome"), "biome", FlowDataType.BIOME, "", "searchable", biomeOptions(), "Optional Biome Restriction").input(PinId.of("min_y"), "min_y", FlowDataType.FLOAT, -64f, "number", List.of(), "Lowest Allowed Block Height").input(PinId.of("max_y"), "max_y", FlowDataType.FLOAT, 319f, "number", List.of(), "Highest Allowed Block Height").input(PinId.of("block_below"), "block_below", FlowDataType.BLOCK, "", "material", List.of(), "Optional Required Block Below The Spawn").input(PinId.of("min_light"), "min_light", FlowDataType.FLOAT, 0f, "number", List.of(), "Lowest Allowed Light Level").input(PinId.of("max_light"), "max_light", FlowDataType.FLOAT, 15f, "number", List.of(), "Highest Allowed Light Level").input(PinId.of("time"), "time", FlowDataType.STRING, "any", "dropdown", List.of("any", "day", "night"), "Allowed Time Of Day").input(PinId.of("weather"), "weather", FlowDataType.STRING, "any", "dropdown", List.of("any", "clear", "rain", "thunder"), "Allowed Weather").input(PinId.of("override_vanilla"), "override_vanilla", FlowDataType.BOOLEAN, false, "toggle", List.of(), "Replace Vanilla Spawns In Matching Biomes").output(PinId.of("spawn"), "spawn", FlowDataType.WORLDGEN_SPAWNS).build());
        registry.register(WorldGenNodeDefinition.builder("output_features", "Output Features").input(PinId.of("placements"), "placements", FlowDataType.WORLDGEN_FEATURES, "", null).build());
        registry.register(WorldGenNodeDefinition.builder("output_structures", "Output Structures").input(PinId.of("placements"), "placements", FlowDataType.WORLDGEN_STRUCTURES, "", null).build());
        registry.register(WorldGenNodeDefinition.builder("output_spawns", "Output Spawns").input(PinId.of("table"), "table", FlowDataType.WORLDGEN_SPAWNS, "", null).build());
    }

    private static List<String> biomeOptions() {
        return List.of();
    }

    private static List<String> entityOptions() {
        return List.of();
    }

    private static List<String> treeOptions() {
        return List.of();
    }

    private static List<String> structureOptions() {
        return List.of();
    }

    private static List<String> featureStages() {
        return List.of("raw_generation", "lakes", "local_modifications", "underground_structures", "surface_structures", "strongholds",
            "underground_ores", "underground_decoration", "fluid_springs", "vegetal_decoration", "top_layer_modification");
    }

    private static List<String> spawnCategories() {
        return List.of("monster", "creature", "ambient", "axolotls", "underground_water_creature", "water_creature", "water_ambient", "misc");
    }
}
